# Build the image
build:
	docker-compose build

# Run the image
up:
	docker-compose up -d

# Show Docker logs
logs:
	docker-compose logs -f


# Clean up all unused Docker resources
clean-all:
	docker system prune --all --force

